<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Disclaimer</title>
<link rel="icon" type="image/png" href="form/assets/img/ico.png">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" >

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container">
	<div class="row">
    	<div class="col-md-10 col-md-offset-1">
                <p><strong>Disclaimer</strong><br />The materials on Tamilpulavar's web site are provided "as is". Tamil Dictionary makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Tamil Dictionary does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.</p>
                <p><strong>Revisions and Errata</strong><br />The materials appearing on this web site could include technical, typographical, or photographic errors. We does not warrant that any of the materials on its web site are accurate, complete, or current. We does not, however, make any commitment to update the materials.</p>
                <p><strong>links</strong><br />We have not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by our site. Use of any such linked web site is at the user's own risk.</p>
                <p><strong>Privacy Policy</strong><br />Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information.</p>
                <p>&nbsp;</p>
                <p><br /><strong>Privacy Policy</strong><br />This Privacy Policy governs the manner in which Tamilpulavar collects, uses, maintains and discloses information collected from users (each, a "User") of the http://Tamilpulavar.com website ("Site"). This privacy policy applies to the Site and all products and services offered by Tamilpulavar.</p>
                <p><strong>Personal identification information</strong><br />We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, place an order, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.</p>
                <p><strong>Non-personal identification information</strong><br />We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>
                <p><strong>Web browser cookies</strong><br />Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p>
                <p><strong>How we use collected information</strong><br />Tamilpulavar may collect and use Users personal information for the following purposes:<br />- To improve customer service<br />Information you provide helps us respond to your customer service requests and support needs more efficiently.<br />- To personalize user experience<br />We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.<br />- To improve our Site<br />We may use feedback you provide to improve our products and services.<br />- To process payments<br />We may use the information Users provide about themselves when placing an order only to provide service to that order. We do not share this information with outside parties except to the extent necessary to provide the service.<br />- To send periodic emails<br />We may use the email address to send User information and updates pertaining to their order. It may also be used to respond to their inquiries, questions, and/or other requests.<br />How we protect your information<br />We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.</p>
                <p><strong>Sharing your personal information</strong><br />We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.</p>
                <p><strong>Advertising</strong><br />Ads appearing on our site may be delivered to Users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile non personal identification information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This privacy policy does not cover the use of cookies by any advertisers.</p>
                <p><strong>Google Adsense</strong><br />Some of the ads may be served by Google. Google's use of the DART cookie enables it to serve ads to Users based on their visit to our Site and other sites on the Internet. DART uses "non personally identifiable information" and does NOT track personal information about you, such as your name, email address, physical address, etc. You may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy at http://www.google.com/privacy_ads.html</p>
                <p><strong>Changes to this privacy policy</strong><br />Tamilpulavar has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.</p>
                <p><strong>Your acceptance of these terms</strong><br />By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</p>
        </div>
    </div>
</div>
</body>
</html>